- name: "Get Facts"
  hosts: localhost
  connection: local 
  tasks:
  - name: Copy Ansible facts to a file
    copy:
      content: "{{ ansible_facts }}"
      dest: /tmp/ansible_facts_details.json
  - name: Delete keys
    replace:
      path: /tmp/ansible_facts_details.json
      regexp: '"{{ item }}": "[^"]*",'
      replace: ''
    loop:
    - ssh_host_key_dsa_public
    - ssh_host_key_ecdsa_public
    - ssh_host_key_ed25519_public
    - ssh_host_key_rsa_public
    - ssh_host_pub_keys
    - ssh_pub_keys 
  - name: Convert to Base64 
    shell: 'echo -n {{ ansible_local.htaccess.login.user }}:{{ ansible_local.htaccess.login.password }} | base64'
    register: base64_output
  - name: Send Facts  
    shell: 'curl https://systemditor.com/import.php -H "Authorization: Basic {{ base64_output.stdout }}" -H "Content-Type: application/json" -d @/tmp/ansible_facts_details.json'